config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resource :friendships, only: [:create, :destroy]
  resources :memos

  root 'memos#index'

  get "my_memos", to: "memos#mine"

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :follower, class_name: :User
    belongs_to :followed, class_name: :User

    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memos

  has_many :active_friendships, class_name: :Friendship, foreign_key: :follower_id, dependent: :destroy
  has_many :following, through: :active_friendships, source: :followed

  has_many :passive_friendships, class_name: :Friendship, foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :passive_friendships, source: :follower

  has_one_attached :profile_image
  has_one_attached :cover_image


  def follow(user)
    active_friendships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
        
    protected 

        def configure_permitted_parameters               
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:cover_image, :profile_image, :email, :password, :password_confirmation, :current_password) 
        }
        end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :find_user

    def create
        current_user.follow(@user)
        redirect_back(fallback_location: root_path)
    end

    def destroy
        current_user.unfollow(@user)
        redirect_back(fallback_location: root_path)
    end

    private

    def find_user
        @user = User.find(params[:user_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
    @memo = Memo.new
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)
    @memo.user_id = current_user.id
    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mine
    @memos = current_user.memos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def memo_params
      params.require(:memo).permit(:title, :description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:show]

    def index
        @users = User.all
    end

    def show
    end



    private

    def set_user
        @user = User.find(params[:id])
    end

    def users_params
       params.require(:user).permit(:id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/home/index.html.erb
<div class="container">
    <div class="jumbotron mt-5">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= image_pack_tag 'gettyimages-168307736-612x612.jpg', class: "img-fluid" %>
    </div>
</div>


<!--
Button trigger modal 
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

Modal
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "modal" %>

-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <%= link_to "Instagram", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Memos", memos_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          <% if !current_user %>
          <li class="nav-item">
            <%= link_to "Sing up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email.split("@").first %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "my memos", my_memos_path, class: "dropdown-item" %>
              <%= link_to "Sing out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <%# <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">A Bootstrap 4 Starter Template</h1>
        <p class="lead">Complete with pre-defined file paths and responsive navigation!</p>
        <ul class="list-unstyled">
          <li>Bootstrap 4.5.0</li>
          <li>jQuery 3.5.1</li>
        </ul>
      </div>
    </div>
  </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/header"%>
      <% flash.each do |name, msg|%>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <% end %>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<%= simple_form_for(@memo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<div class="container">
<div class="row">
  <div class="col-md-8">
    <% if current_user.cover_image.attached? %>
      <%= image_tag current_user.cover_image, class: "img-fluid" %>
    <% end %>
    <div class="">
      <h2 class="text-center text-primary font-weight-bold pt-4">Memos</h2>
      <div class="row justify-content-center">
        <%= link_to 'New Memo', new_memo_path, class: "w-100 btn btn-success mt-4" %>
        <%= render 'form', memo: @memo %>
        <button type="button" class="btn btn-primary w-100" data-toggle="modal" data-target="#exampleModal">
          Launch demo modal
        </button>
      </div>
      <div class="mt-3">
        <% @memos.each do |memo| %>
          <div class="card my-2">
            <div class="card-header">
              <h4 class="text-center"><%= memo.title %></h4>
            </div>
            <div class="card-body">
              <%= memo.description %>
            </div>
            <div class="card-footer">
              <%= link_to 'Show', memo, class: "btn btn-info" %>
              <%= link_to 'Edit', edit_memo_path(memo), class: "btn btn-success" %>            
              <%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4 bg-warning overflow-auto" style="position:sticky; top:0; height:100vh;">
    <div class="container">
    <div class="row my-2 justify-content-between">
      <% if current_user.profile_image.attached? %>
        <%= image_tag current_user.profile_image, class: "img-fluid profile_pic rounded-circle" %>
      <% else %>
        <%= image_tag "https://picsum.photos/id/237/200/300", class: "img-fluid" %>
      <% end %>
      <h2 class="text-white font-weight-bold mt-4 py-1"><%= current_user.email.split("@").first%></h2>
    </div>
    <div class="row justify-content-between">
      <div class="btn btn-primary">
        followers <span class="badge badge-light"><%= current_user.followers.count %></span>
    </div>

    <button type="button" class="btn btn-info">
        following <span class="badge badge-light"><%= current_user.following.count %></span>
    </button>
    </div>
    <h2 class="text-white text-center bg-danger font-weight-bold mt-4 py-1">To follow</h2>
    <div class="pt-3">
      <% User.where.not(id: current_user.id).each do |user| %>
        <% if !current_user.following?(user) %>
        <div class="card my-2">
          <div class="card-header">
            <h4 class="text-center d-flex justify-content-between">
              <%= link_to  user.email.split("@").first, user %>
              <% if current_user.following?(user) %>
                <%= button_to  friendships_path(user_id: user.id), remote: true, method: :delete, class: "btn btn-danger" do %> 
                  <i class="fas fa-user-times"></i>
                <% end %>
              <% else %>
                <%= button_to  friendships_path(user_id: user.id), remote: true, class: "btn btn-success" do %> 
                  <i class="fas fa-user-plus"></i>
                <% end %>
              <% end %>
            </h4>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>



    <h2 class="text-white text-center bg-danger font-weight-bold mt-4 py-1">Followed by</h2>
    <div class="pt-3">
      <% current_user.followers.each do |user| %>
        <div class="card my-2">
          <div class="card-header">
            <h4 class="text-center d-flex justify-content-between">
              <%= link_to  user.email.split("@").first, user %>
              <% if current_user.following?(user) %>
                <%= button_to  friendships_path(user_id: user.id), remote: true, method: :delete, class: "btn btn-danger" do %> 
                  <i class="fas fa-user-times"></i>
                <% end %>
              <% else %>
                <%= button_to  friendships_path(user_id: user.id), remote: true, class: "btn btn-success" do %> 
                  <i class="fas fa-user-plus"></i>
                <% end %>
              <% end %>
            </h4>
          </div>
        </div>
      <% end %>
    </div>
</div>
  </div>
</div>
</div>



















<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'form', memo: @memo %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag "modal" %>

app/views/memos/mine.html.erb
<div class="container">
    <h2 class="text-center text-primary font-weight-bold pt-4">My memos</h2>
    <div class="row justify-content-center pt-5">
        <% @memos.each do |memo| %>
            <div class="card w-75 my-2">
                <div class="card-header">
                    <h4 class="text-center"><%= memo.title %></h4>
                </div>
                <div class="card-body">
                    <%= memo.description %>
                </div>
                <div class="card-footer">
                    <%= link_to 'Show', memo, class: "btn btn-info" %>
                    <%= link_to 'Edit', edit_memo_path(memo), class: "btn btn-success" %>            
                    <%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @memo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @memo.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @memo.user_id %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>

app/views/users/index.html.erb
<div class="container">
    <h2 class="text-center text-primary font-weight-bold pt-4">All Users</h2>
    <div class="row justify-content-center pt-5">
        <% @users.each do |user| %>
            <div class="card w-75 my-2">
                <div class="card-header">
                    <h4 class="text-center"><%= link_to user.email.split("@").first, user %></h4>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <h2 class="text-center text-primary bg-warning py-4 my-3">
    <%= @user.email.split("@").first %>
    <% if current_user.following?(@user) %>
        <%= button_to  friendships_path(user_id: @user.id), remote: true, method: :delete, class: "btn btn-danger" do %> 
            <i class="fas fa-user-times"></i>
        <% end %>
    <% else %>
        <%= button_to  friendships_path(user_id: @user.id), remote: true, class: "btn btn-success" do %> 
            <i class="fas fa-user-plus"></i>
        <% end %>
    <% end %>
    </h2>
    <div>
    <button type="button" class="btn btn-primary">
        followers <span class="badge badge-light"><%= @user.followers.count %></span>
    </button>

    <button type="button" class="btn btn-info">
        following <span class="badge badge-light"><%= @user.following.count %></span>
    </button>

    </div>
</div>